#AMBIENTES DE PRUEBA

#spring.datasource.url=jdbc:mysql://localhost:3306/backendhnm?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#AMBIENTE DE PRODUCCION

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.format_sql=true
spring.datasource.url=jdbc:mysql://uheo2me34mmkly81:TGnu2uRTHt4CCiC4GtN9@bo1zu8mfcdgcyl3bnrub-mysql.services.clever-cloud.com:8080/bo1zu8mfcdgcyl3bnrub
spring.datasource.username=uheo2me34mmkly81
spring.datasource.password=TGnu2uRTHt4CCiC4GtN9

jwt.secret = secret
jwt.expiration = 3600

